In [1]:
# handle missing values
import pandas as pd
import numpy as np
data = {
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
# print(df)

# handle null values
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [3]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder' in df.keys():
  df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding


# handle missing values
import pandas as pd
import numpy as np
data = {
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
# print(df)

# handle null values
df.dropna(inplace=True)
print(df)


   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [2]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder' in df.keys():
  df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding



   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [7]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder' in df.keys():
  df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding (by the help of sklearn)
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['colors']])
print (encoded.toarray())

# one hot encoding (by the help of pandas)
df_encoder = pd.get_dummies(df,columns=['colors'])
print(df_encoder)


   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
   colors_blue  colors_green  colors_orange  colors_red
0        False         False          False        True
1        False          True          False       False
2         True         False          False       False
3        False         False           True       False
4        False          True          False       False
5         True         False          False       False


In [10]:
import numpy as np
import pandas as pd
from sklearn. preprocessing import LabelEncoder , OneHotEncoder
data = {
"age": [10,20, np. nan, 26, 30],
"gender": ['male','female', 'others', 'male',np.nan],
"name": ['dheeraj', 'kavi', 'sapu', 'yash', 'hello']
}
df = pd. DataFrame (data)


# handle missing values
df['age'] = df['age']. fillna(df['age'].mean())
print (df)

SyntaxError: invalid syntax (972238783.py, line 14)