DAY7


In [ ]:
#tuple
t=[10,20,30]
print(t[0])
print([-1])
# example
marks = [98,90,80,95]

#list -> change
# marks[3] = 50
# print (type (marks))
# print (marks)
#tuple -> not change
t = tuple (marks)
print(type(t))
print(t)

#tuple-->list
m = list(t)
print(type(m))
print(m)


10
[-1]
<class 'tuple'>
(98, 90, 80, 95)
<class 'list'>
[98, 90, 80, 95]


DAY7

Commands
        1 python3 -v
        2 python -m venv venv
        3 source venv/bin/activate
        4 then run by python file name
        5 deactivate

In [ ]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
n = numpy.arange(11)
print(type(n))
print (n)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
'''
#example -- 1d
n = numpy.arange(12)

d = n.reshape (3,4) #3 -> rows or 4 -> cols
print(type(d))
print (d)
'''
'''
#example -- 2d
n = numpy.arange(12). reshape(4,3) #--> (4 row , 3 col)
print(n)
'''
#Ex -- 3d
n = numpy.arange(24).reshape(2, 3, 4) #----->2x3x4=24 so arange is 24(2 = matrix , 3 =row , 4=column)

print(n)
print(n.ndim)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


'\nn = numpy.arange(24).reshape(2, 3, 4) #----->2x3x4=24 so arange is 24(2 = matrix , 3 =row , 4=column)\n\nprint(n)\nprint(n.ndim)\n'

In [ ]:
#spliting
from re import split
n = numpy.arange(12). reshape (4,3)
print(n)
# example split # 2,5,8,11 -> print


'''
print(n[:,2])  #first ":" is for all row 2 is for column
print(n[0:4:,2])         #works on jump
print(n[0:4:,2:4])
print(n[:,-1])
'''
#print 4 and 7
print(n[1:3,1])
#or
print(n[1:3,1:2])




[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 1  4  7 10]
[4 7]
[[4]
 [7]]


In [ ]:
n=

 #DAY-10 (NUMPY)


creating array from list
1. 1d
2. 2d

In [ ]:
import numpy as np
#list
print("1D list and array","\n")
l = [1,2,3]
print(l)


#numpy - array
arr = np.array(l)

print(arr,"\n")
print("2D list and array","\n")
#2d array
l2 = [[1,2,3],
      [4,5,6]]
print(l2)
arr2 = np.array([[1,2,3,],[4,5,6]])
#or arr2 = np.array(l2)              #because it accepts only 1 argument
print(arr2)
print(arr2[0])                #print row 1
print(arr2[0][0])             #row 1 col1


#modify one value
arr2[1][0]=100
l2[1][0]=100
print(arr2)
print(l2)

#3d
print("3D list and array","\n")




1D list and array 

[1, 2, 3]
[1 2 3] 

2D list and array 

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[  1   2   3]
 [100   5   6]]
[[1, 2, 3], [100, 5, 6]]
3D list and array 



#list vs numpy array
1. Example of multi with list and array
2. time comparsion
3. zeros (3,4)
4. ones (2,3)
5. full ((2,2),7)
6. random (2,3)
7. arange (0,10,2)

In [ ]:
#1. Example of multi with list and array
import numpy as np
l = [1,2,3]
lm = l*2
print(lm)

arr=np.array(l)
arrm=arr*2
print(arrm)





[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
#2. Time Comparsion
#list
import time
start = time.time()
l=[i*2 for i in range(1000000)]          #more 0 better comparision
end = time.time()
print("List's output")
print(end-start)

#array
import numpy as np
start = time.time()
arr = np.array(1000000)
arr = arr*2
end = time.time()
print("Array's output")
print(end-start)

List's output
0.13236665725708008
Array's output
0.00017833709716796875


In [ ]:
#3. zeros (3,4)
import numpy as np
#one D
arr =np.zeros(5)
print(arr)
#2D
arr2 = np.zeros((3,4))
print(arr2)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones array
#1D
import numpy as np
arr=np.ones(5)
print(arr)

#2D
arr2=np.ones((3,4))
print(arr2)



[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Q - By help of zeros make 2d arry then add each by 10 and by ones mul each by 10
import numpy as np
arr=np.zeros((3,4))+10
print(arr)

arr1=np.ones((3,4))*10
print(arr1)


[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [ ]:
#5.full for 2d
import numpy as np
arr = np.full((2,3),10)
print(arr)

[[10 10 10]
 [10 10 10]]


In [ ]:
#Q = by help of zeros
import numpy as np
arr= np.zeros((3,4))+6
arr1 = np.full((3,4),1)
print(arr)
print(arr1)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#6.random(0 to 1 random number)
import numpy as np
arr=np.random.random(5)
print(arr)

#2D    0 -> 1
arr2=np.random.random((3,4))
print(arr2)

[0.46236364 0.23733357 0.94106776 0.14780867 0.73309974]
[[0.69624761 0.76858724 0.7105285  0.6348788 ]
 [0.52433466 0.24496704 0.83461555 0.90723518]
 [0.26949596 0.64832328 0.27377457 0.29245558]]


In [ ]:
#7.arange()
import numpy as np
#1D
arr=np.arange(5)           #arange 0 to 4 in a line
print(arr)

arr1=np.arange(10,20)      #arange 10 to 19 in a line
print(arr1)

#start , stop ,step
arr3=np.arange(10,20,2)
print(arr3)

#2D(for this we use reshape)
arr2=np.arange(12).reshape(3,4)       #arange 0 to 11 in 3 by 4 matrix (i.e. 3*4=12)
print(arr2)

[0 1 2 3 4]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#Vector, matrix,tensor
1. vector (1d)
2. matrix (2d)
3. tensor (3d)


In [ ]:
#1. vector(1d)
#list
l = [1,2,3]
print(l)
#array
arr = np.array([1,2,3])
print(arr)



[1, 2, 3]
[1 2 3]


In [ ]:

#2. matrix
#list
l = [[1,2,3],
     [4,5,6]]
print(l)
#array
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#3.tensor
#list
l = [[[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]]
print(l)
#array
arr = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(arr)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#Array properties
1. shape
2. dimension
3. size
4. dtype

In [ ]:
import numpy as np
#1.shape
arr=np.arange(12)
print("Shape",arr.shape)

arr2=np.arange(12).reshape(3,4)
print("Shape",arr2.shape)

#2.dimension
print("Dimension",arr.ndim)
print("Dimension",arr2.ndim)

#3.size
print("Size",arr.size)
print("Size",arr2.size)

#4.dtype
print("Datatype",arr.dtype)


Shape (12,)
Shape (3, 4)
Dimension 1
Dimension 2
Size 12
Size 12
Datatype int64


#Array Reshaping

1.reshape()

2.flatten() -> create copy

3.ravel() -> return original

4.transpose



In [ ]:
#reshape array
'''
import numpy as np
arr=np.arange(12)       #  -->12 can be in( 3,4)(6,2)(12,1)
up_arr=np.reshape(arr,(3,4))   #3-->row
print(up_arr)
'''

#example to make a 3d array
import numpy as np
arr=np.arange(12)
up_arr=np.reshape(arr,(2,3,2))
print(up_arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
#flatten()
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)
flat_arr=arr.flatten()
print(flat_arr)


#for 3d
arr=np.arange(12).reshape(2,3,2)
print(arr)
flat_arr=arr.flatten()
print(flat_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#ravel-----> work on org value if we change a value in flat arr then it change org value
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)
flat_arr=arr.ravel()
print(flat_arr)

#changing org value

flat_arr[0]=20
print("Original array")
print(arr)

#3d
arr=np.arange(12).reshape(2,3,2)
print(arr)
flat_arr=arr.ravel()
print(flat_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Original array
[[20  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#transpose
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)
trans_arr=arr.transpose()
print(trans_arr)

#for 3d
arr=np.arange(12).reshape(2,3,2)
print("3d array")
print(arr)
trans_arr=arr.transpose()
print(trans_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
3d array
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
#slicing in 1d array
import numpy as np
arr=np.arange(11)
print(arr)
up_arr = arr[:3]
print(up_arr)

#for 2d
arr=np.arange(12).reshape(3,4)
print(arr)
up_arr=arr[:,-1]
print(up_arr)

#for print index 0 and 23 in 3d
arr=np.arange(24).reshape(2,3,4)     #2 table , 3row, 4col
print(arr)
up_arr = arr[0,0,0]
print(up_arr)
up_arr = arr[1,2,3]
print(up_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
23


#looping with numpy
1.while loop

2.for loop

In [ ]:
# while loop
# while loop for 1d

import numpy as np
arr = np.arange(12)
i = 0
while i < len(arr):
  print (arr[i], end=" ")
  i += 1
print()
print()
# while loop for 2d
import numpy as np
arr = np.arange(12).reshape(3,4)
i=0
while i < len(arr):
  j=0
  while j < len(arr[i]):
    print(arr[i][j], end=" ")
    j += 1
  print()
  i += 1





0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 


In [ ]:
# while loop for 3d
arr = np.arange(24).reshape(2, 3, 4)

i = 0
while i < len(arr):
  j = 0
  while j < len(arr[i]):
    k = 0
    while k < len(arr[i][j]):
      print(arr[i][j][k], end=" ")
      k += 1
    print()
    j += 1
  print()
  i += 1

0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



In [ ]:
#for loop
#print 1d array
import numpy as np
arr = np.arange(12)
for i in arr:
  print(i, end=" ")
print()
print()

#print 2d
import numpy as np
arr = np.arange(12).reshape(3,4)
for i in arr:
  for j in i:
    print(j, end=" ")
  print()
print()


#print 3d array
import numpy as np
arr = np.arange(24).reshape(2,3,4)
for i in arr:
  for j in i:
    for k in j:
      print(k, end=" ")
    print()
  print()


0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 4 5 6 7 8 9 10 11 
0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



DAY10

#Sorting
1.sort() for 1d
2.sort(). for 2d,use axis=0-->col

In [6]:
#sort
#1d
import numpy as np
arr=np.array([10,20,5,22,40,30])
print(arr)
#arr.sort()
#or
arr_s=np.sort(arr)
print(arr_s)



#2d
import numpy as np
arr1=np.array([[10,20,5,22,40,30],
              [1,2,3,4,5,6]])
print(arr1)
arr1_s=np.sort(arr1,axis=0)    #-->by defalt row wise sort
print(arr1_s)



#example
import numpy as np
arr2=np.array([[10,20,5,22,40,30],
              [1,2,3,4,5,6]])
print(arr2)
arr2_s=np.sort(arr2,axis=1)      #same if we dont use axis
print(arr2_s)

[10 20  5 22 40 30]
[ 5 10 20 22 30 40]
[[10 20  5 22 40 30]
 [ 1  2  3  4  5  6]]
[[ 1  2  3  4  5  6]
 [10 20  5 22 40 30]]
[[10 20  5 22 40 30]
 [ 1  2  3  4  5  6]]
[[ 5 10 20 22 30 40]
 [ 1  2  3  4  5  6]]


In [14]:
#by defalt assending but in descending
import numpy as np
arr=np.array([1,34,22,12,5,2])
arr_desc = np.sort(arr)[::-1]
print(arr_desc)
#2d
import numpy as np
arr2=np.array([[10,20,2,22,40,30],
              [1,2,3,4,5,6]])
print(arr2)
arr2_desc=np.sort(arr2,axis=0)[::-1]     #[start : stop : step]
print(arr2_desc)

[34 22 12  5  2  1]
[[10 20  2 22 40 30]
 [ 1  2  3  4  5  6]]
[[10 20  3 22 40 30]
 [ 1  2  2  4  5  6]]


#filter
1.array[Expression]


In [18]:
import numpy as np
arr=np.array([20,10,8,25,2])
print(arr)
arr_f=arr[arr<15]
print(arr_f)

#ex
import numpy as np
arr=np.array([[20,10,8,25,2],[3,49,3,4,5]])
print(arr)
arr_f=arr[arr%4==0]
print(arr_f)

[20 10  8 25  2]
[10  8  2]
[[20 10  8 25  2]
 [ 3 49  3  4  5]]
[20  8  4]


In [25]:
#np.where      like conditional
import numpy
# 1d
arr =np.array ([10,3,4,80,30,40,9])
print (arr)
arr_w = np.where(arr>40, "True", "False")
print (arr_w)
#


arr1 =np.array ([10,3,4,80,30,40,9])
print (arr)
arr_w = np.where(arr1>40, arr1+2, arr1-2)
#if arr>40
#arr+2
#else
    #arr-2
print (arr_w)

#example2
print("example 2")
import numpy as np
arr3 = np.array([[10,20,30,40,50],[111,22,33,444,55,]])
print(arr)
arr_w = np.where(arr>40, arr+2, arr-2)
print(arr_w)

[10  3  4 80 30 40  9]
['False' 'False' 'False' 'True' 'False' 'False' 'False']
[10  3  4 80 30 40  9]
[ 8  1  2 82 28 38  7]
example 2
[10  3  4 80 30 40  9]
[ 8  1  2 82 28 38  7]


In [30]:
# concatenate
# 1d
import numpy as np
arrl = np.array([10,20,30])
arr2 = np.array([1,2,3])
#concatenate method
arrl_arr2 = np.concatenate( (arrl,arr2))
print (arrl_arr2)
# manually
arr1_arr2_new = arrl + arr2
print (arr1_arr2_new)

# example 2d
import numpy as np
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)

#example 2d array concatenate
import numpy as np
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([[70,80,90], [100,110,120]])
print(np.concatenate((arr1,arr2), axis = 0))  #--->row
print(np.concatenate((arr1,arr2), axis = 1))  #-->col




[10 20 30  1  2  3]
[11 22 33]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]


#Statistical Functions
D
1. np.sum(a) -> Sum of all elements
く＞
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.medilin(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean, difference, square, average | (sum = ddof) -> divide by array length

7. np.std(a) -> Standard Deviation = root(Variance) -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
11. np.argmin(a) -> Index position of minimum value
12. np.argmax(a) -> Index position of maximum value
13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a) -> Returns unique values only -> Removes duplicates
15. np.percerftile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%

17. np.ptp(a) -> Range = Max - Min
田
18. np.any(a) -> True if at least one value is True

In [41]:
# statistical Functions
#sum
import numpy as np
arr = np.array([2,3,5])
print(arr)
arr1 = np.sum(arr)

print("--------Add all elements-------- ")
print("sum : ",arr1)


#mean
import numpy as np
arr = np.array([2,3,5])
arr1 = np.mean(arr)
print("--------Average-------- ")
print("mean : ",arr1)

#median
import numpy as np
arr = np.array([2,3,4])
arr1 = np.median(arr)
print("--------Sort then find middle element-------- ")
print("median : ",arr1)

#min
import numpy as np
arr = np.array([2,3,5])
arr1 = np.min(arr)
print("--------Minimum element of array-------- ")
print("min : ",arr1)
#max
import numpy as np
arr = np.array([2,3,5])
arr1 = np.max(arr)
print("--------Maximum element of array-------- ")
print("max : ",arr1)
#var
import numpy as np
arr = np.array([2,3,5])
arr1 = np.var(arr)
print("--------Variance(avg of std)-------- ")
print("variance : ",arr1)
#std
import numpy as np
arr = np.array([2,3,5])
arr1 = np.std(arr)
print("--------Standard Deviation (2-mean) ka whole square similar for each element then there sum-------- ")
print("std : ",arr1)
#prod
import numpy as np
arr = np.array([2,3,5])
arr1 = np.prod(arr)
print("prod : ",arr1)
#cumsum
import numpy as np
arr = np.array([2,3,5])
arr1 = np.cumsum(arr)
print(arr1)
#cumprod
import numpy as np
arr = np.array([2,3,5])
arr1 = np.cumprod(arr)
print(arr1)
#argmin
import numpy as np
arr = np.array([2,3,5])
arr1 = np.argmin(arr)
print("argmin : ",arr1)
#argman
import numpy as np
arr = np.array([2,3,5])
arr1 = np.argmax(arr)
print("argmax : ",arr1)
#abs
import numpy as np
arr = np.array([2,3,5])
arr1 = np.abs(arr)
print(arr1)
#unique
import numpy as np
arr = np.array([2,3,5,2,3,5])
print(arr)
arr1 = np.unique(arr)
print(arr1)
#np.percentile(a,50)
import numpy as np
arr = np.array([2,3,5])
arr1 = np.percentile(arr,50)
print("percentile : ",arr1)
# np.quantile()
import numpy as np
arr = np.array([2,3,5])

arr1 = np.quantile(arr,0.5)
print("quantile : ",arr1)

#ptp
import numpy as np
arr = np.array([2,3,5])

arr1 = np.ptp(arr)
print("ptp : ",arr1)
#any
import numpy as np
arr = np.array([2,3,5])

arr1 = np.any(arr)
print("any : ",arr1)

[2 3 5]
--------Add all elements-------- 
sum :  10
--------Average-------- 
mean :  3.3333333333333335
--------Sort then find middle element-------- 
median :  3.0
--------Minimum element of array-------- 
min :  2
--------Maximum element of array-------- 
max :  5
--------Variance(avg of std)-------- 
variance :  1.5555555555555554
--------Standard Deviation (2-mean) ka whole square similar for each element then there sum-------- 
std :  1.247219128924647
prod :  30
[ 2  5 10]
[ 2  6 30]
argmin :  0
argmax :  2
[2 3 5]
[2 3 5 2 3 5]
[2 3 5]
percentile :  3.0
quantile :  3.0
ptp :  3
any :  True
