DAY7


In [ ]:
#tuple
t=[10,20,30]
print(t[0])
print([-1])
# example
marks = [98,90,80,95]

#list -> change
# marks[3] = 50
# print (type (marks))
# print (marks)
#tuple -> not change
t = tuple (marks)
print(type(t))
print(t)

#tuple-->list
m = list(t)
print(type(m))
print(m)


10
[-1]
<class 'tuple'>
(98, 90, 80, 95)
<class 'list'>
[98, 90, 80, 95]


DAY7

Commands
        1 python3 -v
        2 python -m venv venv
        3 source venv/bin/activate
        4 then run by python file name
        5 deactivate

In [2]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
n = numpy.arange(11)
print(type(n))
print (n)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
'''
#example -- 1d
n = numpy.arange(12)

d = n.reshape (3,4) #3 -> rows or 4 -> cols
print(type(d))
print (d)
'''
'''
#example -- 2d
n = numpy.arange(12). reshape(4,3) #--> (4 row , 3 col)
print(n)
'''
#Ex -- 3d
n = numpy.arange(24).reshape(2, 3, 4) #----->2x3x4=24 so arange is 24(2 = matrix , 3 =row , 4=column)

print(n)
print(n.ndim)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


'\nn = numpy.arange(24).reshape(2, 3, 4) #----->2x3x4=24 so arange is 24(2 = matrix , 3 =row , 4=column)\n\nprint(n)\nprint(n.ndim)\n'

In [35]:
#spliting
from re import split
n = numpy.arange(12). reshape (4,3)
print(n)
# example split # 2,5,8,11 -> print


'''
print(n[:,2])  #first ":" is for all row 2 is for column
print(n[0:4:,2])         #works on jump
print(n[0:4:,2:4])
print(n[:,-1])
'''
#print 4 and 7
print(n[1:3,1])
#or
print(n[1:3,1:2])




[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 1  4  7 10]
[4 7]
[[4]
 [7]]


In [ ]:
n=